CREATE TABLE account 
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	account_id VARCHAR(100) NOT NULL,
	hashed_passwd VARCHAR(40) NOT NULL,
	timestamp TIMESTAMP NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
);
