CREATE TABLE account 
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	account VARCHAR(100) NOT NULL,
	hashed_passwd VARCHAR(40) NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
