CREATE TABLE system
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE city
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
);

CREATE TABLE pointer
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
);

CREATE TABLE system_city
(
	system_id INT UNSIGNED NOT NULL;
	city_id INT UNSIGNED NOT NULL;
);

CREATE TABLE city_pointer
(
	city_id INT UNSIGNED NOT NULL;
	pointer_id INT UNSIGNED NOT NULL;
);
